/* Define POLLIN values manually if not defined by some compiler */
#ifndef POLLIN
	#define POLLIN 0x001
	#define POLLPRI 0x002
	#define POLLOUT 0x004
	#define POLLERR 0x008
	#define POLLHUP 0x010
	#define POLLNVAL 0x020
	#define POLLRDNORM 0x100
	#define POLLRDBAND 0x200
	#define POLLWRNORM 0x010
	#define POLLWRBAND 0x400
#endif

/* Operation would block */
#define EWOULDBLOCK WSAEWOULDBLOCK 
#define EAGAIN WSAEWOULDBLOCK

/* Operation now in progress */
#define EINPROGRESS WSAEINPROGRESS 
#define EALREADY WSAEALREADY 

/* Socket errors */
#define ENOTSOCK WSAENOTSOCK 
#define EDESTADDRREQ WSAEDESTADDRREQ 
#define EMSGSIZE WSAEMSGSIZE 
#define EPROTOTYPE WSAEPROTOTYPE 
#define ENOPROTOOPT WSAENOPROTOOPT 
#define EPROTONOSUPPORT WSAEPROTONOSUPPORT 
#define ESOCKTNOSUPPORT WSAESOCKTNOSUPPORT 
#define EOPNOTSUPP WSAEOPNOTSUPP 
#define EPFNOSUPPORT WSAEPFNOSUPPORT 
#define EAFNOSUPPORT WSAEAFNOSUPPORT 

/* Address errors */
#define EADDRINUSE WSAEADDRINUSE 
#define EADDRNOTAVAIL WSAEADDRNOTAVAIL 

/* Network subsystem errors */
#define ENETDOWN WSAENETDOWN 
#define ENETUNREACH WSAENETUNREACH 
#define ENETRESET WSAENETRESET 

/* Connection errors */
#define ECONNABORTED WSAECONNABORTED 
#define ECONNRESET WSAECONNRESET 
#define ENOBUFS WSAENOBUFS 
#define EISCONN WSAEISCONN 
#define ENOTCONN WSAENOTCONN 
#define ESHUTDOWN WSAESHUTDOWN 
#define ETIMEDOUT WSAETIMEDOUT 
#define ECONNREFUSED WSAECONNREFUSED 

/* Host errors */
#define EHOSTUNREACH WSAEHOSTUNREACH 

/* Some misc stuff */
#define EINTR WSAEINTR
#define EFAULT WSAEFAULT 
#define EINVAL WSAEINVAL 
#define EMFILE WSAEMFILE 
#define EACCES WSAEACCES 
#define EPERM WSAEACCES
#define ENOMEM WSA_NOT_ENOUGH_MEMORY 
