name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install autoconf
      run: sudo apt install autoconf-archive
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: install mock
      run: sudo apt install mock tito
    - name: build rpm
      run: tito build --builder mock --arg mock=epel-7-x86_64 --rpm --output /tmp/results --dist ".el7"
    - name: Update release
      uses: johnwbyrd/update-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./tmp/results/*.rpm

